[package]
name = "entab-r"
version = "0.3.1"
authors = ["Roderick <rbovee@gmail.com>"]
edition = "2018"

[dependencies]
entab_base = { package = "entab", git = "https://github.com/murphy-osmo/entab" }
extendr-api = "0.4.0"
libR-sys = "0.4.0"

[lib]
name = "entab"
crate-type = ["cdylib"]
